name: Code quality

on:
  push:
    branches: [ master ] # Adjust branches as needed
  pull_request:
    branches: [ master ] # Adjust branches as needed

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - name: Setup Biome
        uses: biomejs/setup-biome@f382a98e582959e6aaac8e5f8b17b31749018780 # v2.5.0
        with:
          version: latest
      - name: Run Biome
        run: biome ci ./src --reporter=github
